"""Deterministic Codex-compatible smoke runner for release and integration tests."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

CREATED_AT = "2026-05-19T12:00:00Z"


def _terminal_token_for_prompt(prompt: str) -> str:
    normalized = prompt.lower()
    stage_kind = _prompt_field(prompt, "Stage Kind ID").lower()
    stage = _prompt_field(prompt, "Stage").lower()
    if stage_kind == "manager_blueprint":
        return "MANAGER_BLUEPRINT_COMPLETE"
    if stage_kind == "contractor_blueprint":
        return "BLUEPRINT_CANDIDATE_READY"
    if stage_kind == "evaluator_blueprint":
        return "BLUEPRINT_APPROVED"
    if stage_kind == "mechanic_blueprint":
        return "MECHANIC_BLUEPRINT_COMPLETE"
    if stage == "planner":
        return "PLANNER_COMPLETE"
    if stage == "manager":
        return "MANAGER_COMPLETE"
    if stage == "checker":
        return "CHECKER_PASS"
    if stage == "updater":
        return "UPDATE_COMPLETE"
    if stage == "arbiter":
        return "ARBITER_COMPLETE"
    if "stage: checker" in normalized:
        return "CHECKER_PASS"
    if "stage: updater" in normalized:
        return "UPDATE_COMPLETE"
    return "BUILDER_COMPLETE"


def _prompt_field(prompt: str, label: str) -> str:
    prefix = f"{label}: "
    for line in prompt.splitlines():
        if line.startswith(prefix):
            return line.removeprefix(prefix).strip()
    return ""


def _active_work_item(prompt: str) -> tuple[str, str]:
    raw = _prompt_field(prompt, "Active Work Item")
    parts = raw.split()
    if len(parts) >= 2:
        return parts[0], parts[1]
    return "none", "none"


def _materialize_blueprint_artifacts(prompt: str, token: str) -> None:
    run_dir_text = _prompt_field(prompt, "Run Directory")
    if not run_dir_text:
        return
    run_dir = Path(run_dir_text)
    run_dir.mkdir(parents=True, exist_ok=True)
    if token == "MANAGER_BLUEPRINT_COMPLETE":
        _write_manager_blueprint_artifacts(prompt, run_dir)
    elif token == "BLUEPRINT_CANDIDATE_READY":
        _write_contractor_blueprint_artifacts(prompt, run_dir)
    elif token == "BLUEPRINT_APPROVED":
        _write_evaluator_blueprint_artifacts(prompt, run_dir)
    elif token == "ARBITER_COMPLETE":
        _write_arbiter_artifacts(prompt)


def _write_manager_blueprint_artifacts(prompt: str, run_dir: Path) -> None:
    source_kind, source_id = _active_work_item(prompt)
    root_spec_id = source_id if source_kind == "spec" else f"spec-{source_id}"
    root_idea_id = f"idea-{root_spec_id}"
    manifest_id = f"manifest-{root_spec_id}"
    draft_ids = (f"draft-{root_spec_id}-001", f"draft-{root_spec_id}-002")
    manifest = {
        "manifest_id": manifest_id,
        "root_spec_id": root_spec_id,
        "root_idea_id": root_idea_id,
        "source_work_item_kind": source_kind if source_kind in {"spec", "incident"} else "spec",
        "source_work_item_id": source_id,
        "source_spec_id": root_spec_id,
        "draft_ids": list(draft_ids),
        "draft_count": len(draft_ids),
        "spec_summary": "Smoke Blueprint Planning output.",
        "decomposition_strategy": "Two strict-sequence smoke drafts.",
        "global_acceptance_intent": ["Smoke-generated tasks complete."],
        "integration_boundary_notes": ["Generated by deterministic smoke shim."],
        "risk_notes": ["Smoke artifacts are intentionally minimal."],
        "references": ["tests/integration/codex_smoke_shim.py"],
        "created_at": CREATED_AT,
    }
    drafts = [
        _draft_payload(
            draft_id=draft_ids[0],
            manifest_id=manifest_id,
            root_spec_id=root_spec_id,
            root_idea_id=root_idea_id,
            draft_index=1,
            depends_on_draft_ids=[],
        ),
        _draft_payload(
            draft_id=draft_ids[1],
            manifest_id=manifest_id,
            root_spec_id=root_spec_id,
            root_idea_id=root_idea_id,
            draft_index=2,
            depends_on_draft_ids=[draft_ids[0]],
        ),
    ]
    _write_json(run_dir / "blueprint_manifest.json", manifest)
    _write_json(run_dir / "blueprint_drafts.json", drafts)


def _draft_payload(
    *,
    draft_id: str,
    manifest_id: str,
    root_spec_id: str,
    root_idea_id: str,
    draft_index: int,
    depends_on_draft_ids: list[str],
) -> dict[str, object]:
    return {
        "draft_id": draft_id,
        "manifest_id": manifest_id,
        "root_spec_id": root_spec_id,
        "root_idea_id": root_idea_id,
        "source_spec_id": root_spec_id,
        "draft_index": draft_index,
        "depends_on_draft_ids": depends_on_draft_ids,
        "title": f"Smoke Draft {draft_index}",
        "summary": f"Smoke Blueprint draft {draft_index}.",
        "scope": ["README.md"],
        "target_paths": ["README.md"],
        "acceptance_intent": [f"Smoke draft {draft_index} completes."],
        "verification_intent": ["millrace status"],
        "integration_boundary_notes": ["Generated by deterministic smoke shim."],
        "context_excerpt": "Smoke Blueprint context.",
        "current_revision": 0,
        "references": ["tests/integration/codex_smoke_shim.py"],
        "created_at": CREATED_AT,
    }


def _write_contractor_blueprint_artifacts(prompt: str, run_dir: Path) -> None:
    draft = _load_active_blueprint_draft(prompt)
    revision = int(draft.get("current_revision", 0)) + 1
    blueprint_id = f"blueprint-{draft['draft_id']}-r{revision}"
    references = ["tests/integration/codex_smoke_shim.py"]
    latest_critique_id = draft.get("latest_critique_id")
    if latest_critique_id:
        references.append(f"millrace-agents/blueprints/critiques/open/{latest_critique_id}.json")
    packet = {
        "blueprint_id": blueprint_id,
        "draft_id": draft["draft_id"],
        "manifest_id": draft["manifest_id"],
        "root_spec_id": draft["root_spec_id"],
        "root_idea_id": draft["root_idea_id"],
        "revision": revision,
        "title": f"Smoke Blueprint {draft['draft_id']}",
        "implementation_scope": ["Smoke implementation scope."],
        "intended_files": ["README.md"],
        "design_decisions": ["Use deterministic smoke output."],
        "verification_plan": ["millrace status"],
        "task_acceptance": [f"{draft['draft_id']} smoke task completes."],
        "required_checks": ["millrace status"],
        "risk_notes": ["Smoke-only artifact."],
        "references": references,
        "created_at": CREATED_AT,
    }
    _write_json(run_dir / "blueprint_packet.json", packet)
    (run_dir / "blueprint.md").write_text(f"# {packet['title']}\n\nSmoke packet.\n", encoding="utf-8")


def _write_evaluator_blueprint_artifacts(prompt: str, run_dir: Path) -> None:
    draft = _load_active_blueprint_draft(prompt)
    blueprint_id = draft.get("latest_" "blueprint_id") or f"blueprint-{draft['draft_id']}-r1"
    evaluation_id = f"evaluation-{blueprint_id}"
    evaluation = {
        "evaluation_id": evaluation_id,
        "blueprint_id": blueprint_id,
        "draft_id": draft["draft_id"],
        "manifest_id": draft["manifest_id"],
        "root_spec_id": draft["root_spec_id"],
        "root_idea_id": draft["root_idea_id"],
        "decision": "approved",
        "rubric_findings": ["Smoke Blueprint is acceptable."],
        "lineage_consistency_findings": ["Lineage matches active draft."],
        "verification_findings": ["Smoke check present."],
        "required_task_fields": ["task_id", "target_paths", "acceptance", "required_checks"],
        "references": ["tests/integration/codex_smoke_shim.py"],
        "created_at": CREATED_AT,
    }
    _write_json(run_dir / "blueprint_evaluation.json", evaluation)
    _write_json(
        run_dir / "generated_task.json",
        _generated_task_payload(draft, blueprint_id=blueprint_id),
    )


def _generated_task_payload(draft: dict[str, object], *, blueprint_id: str) -> dict[str, object]:
    task_id = f"task-{draft['draft_id']}"
    return {
        "task_id": task_id,
        "title": f"Smoke Task {draft['draft_id']}",
        "summary": "Smoke generated Blueprint task.",
        "root_idea_id": draft["root_idea_id"],
        "root_spec_id": draft["root_spec_id"],
        "spec_id": draft["source_spec_id"],
        "target_paths": ["README.md"],
        "acceptance": [f"{draft['draft_id']} smoke task completes."],
        "required_checks": ["millrace status"],
        "references": [
            "tests/integration/codex_smoke_shim.py",
            f"millrace-agents/blueprints/packets/approved/{blueprint_id}.json",
        ],
        "risk": ["Smoke-only artifact."],
        "created_at": CREATED_AT,
        "created_by": "evaluator_blueprint",
    }


def _write_arbiter_artifacts(prompt: str) -> None:
    verdict_path = _prompt_field(prompt, "Preferred Verdict Path")
    report_path = _prompt_field(prompt, "Preferred Report Path")
    if verdict_path and verdict_path != "none":
        path = Path(verdict_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text('{"status":"pass"}\n', encoding="utf-8")
    if report_path and report_path != "none":
        path = Path(report_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("# Smoke Arbiter Report\n\nPass.\n", encoding="utf-8")


def _load_active_blueprint_draft(prompt: str) -> dict[str, object]:
    active_path = _prompt_field(prompt, "Active Work Item Path")
    if not active_path or active_path == "none":
        raise RuntimeError("Blueprint smoke stage requires Active Work Item Path")
    return json.loads(Path(active_path).read_text(encoding="utf-8"))


def _write_json(path: Path, payload: object) -> None:
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("-c", dest="config", action="append", default=[])
    parser.add_argument("--profile")
    parser.add_argument("--skip-git-repo-check", action="store_true")
    parser.add_argument("--model")
    parser.add_argument("--full-auto", action="store_true")
    parser.add_argument("--dangerously-bypass-approvals-and-sandbox", action="store_true")
    parser.add_argument("--sandbox")
    parser.add_argument("--cd")
    parser.add_argument("--output-last-message", required=True)
    parser.add_argument("prompt")
    args, _unknown = parser.parse_known_args()

    if args.cd:
        os.chdir(args.cd)

    token = _terminal_token_for_prompt(args.prompt)
    _materialize_blueprint_artifacts(args.prompt, token)
    output = f"### {token}\n"
    Path(args.output_last_message).write_text(output, encoding="utf-8")
    print(output, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
