"""Shared contract types."""

from __future__ import annotations

from .contract_core import (
    ACCEPTANCE_ID_RE,
    CARD_HEADING_RE,
    FIELD_LINE_RE,
    PUBLIC_V1_EXECUTION_STATUSES,
    PUBLIC_V1_RESEARCH_STATUSES,
    PUBLIC_V1_STAGE_TYPES,
    REQUIREMENT_ID_RE,
    ContractModel,
    ContractSurface,
    ExecutionStatus,
    ReasoningEffort,
    ResearchMode,
    ResearchStatus,
    RunnerKind,
    SpecInterviewPolicy,
    StageType,
    TOKEN_RE,
    _extract_field_block_lines,
    _extract_field_tokens,
    _extract_field_value,
    _normalize_datetime,
    _normalize_integration_preference,
    _normalize_path,
    _normalize_sequence,
    _normalize_tokens,
    _slugify_task_id,
    execution_status_surface,
    research_status_surface,
    stage_surface,
)


# Runtime-facing stage and recovery contracts live in a sibling module but
# remain re-exported here to keep the shared contracts facade stable.
from .contract_runtime import (
    CodexUsageSummary,
    CrossPlaneParentRun,
    ExecutionResearchHandoff,
    ResearchRecoveryDecision,
    ResearchRecoveryLatch,
    RunnerResult,
    StageContext,
)

from .contract_documents import TaskCard


from .contract_documents import (
    AuditContract,
    AuditExecutionFinding,
    AuditExecutionReport,
    AuditGateDecision,
    AuditGateDecisionCounts,
    BlockerEntry,
    CompletionDecision,
    CompletionManifest,
    CompletionManifestCommand,
    ObjectiveCompletionPolicy,
    ObjectiveContract,
    StageResult,
    load_objective_contract,
)
from .contract_compounding import (
    COMPOUNDING_SCHEMA_VERSION,
    InjectedProcedure,
    ProcedureInjectionBundle,
    ProcedureLifecycleRecord,
    ProcedureLifecycleState,
    ProcedureRetrievalRule,
    ProcedureScope,
    ProcedureUsageDisposition,
    ProcedureUsageRecord,
    ReusableProcedureArtifact,
)
from .contract_context_facts import (
    CONTEXT_FACT_SCHEMA_VERSION,
    ContextFactArtifact,
    ContextFactLifecycleState,
    ContextFactScope,
)

# Phase 01B loop-architecture contracts live in a dedicated module but remain
# re-exported here to preserve the existing shared-contract import surface.
from .loop_architecture import (
    AcceptanceProfile,
    ArtifactMultiplicity,
    ArtifactPersistence,
    CardCountRange,
    ControlPlane,
    EdgeAlwaysCondition,
    EdgeArtifactPresentCondition,
    EdgeFactEqualsCondition,
    GateStrictness,
    LoopArchitectureCatalog,
    LoopConfigDefinition,
    LoopConfigPayload,
    LoopEdge,
    LoopEdgeCondition,
    LoopEdgeKind,
    LoopStageNode,
    LoopStageNodeOverrides,
    LoopTerminalClass,
    LoopTerminalState,
    ModeCompositionRules,
    ModeDefinition,
    ModePayload,
    ModePolicyToggles,
    ModelBinding,
    ModelProfileDefinition,
    ModelProfilePayload,
    OutlineMode,
    OutlinePolicy,
    PersistedArchitectureObject,
    PersistedObjectKind,
    PersistedObjectStatus,
    RegistryObjectRef,
    RegistryObjectSource,
    RegistrySourceKind,
    RegistryTier,
    RegisteredStageKindDefinition,
    RegisteredStageKindPayload,
    ResearchAssumption,
    ResearchParticipationMode,
    ScopedModelBinding,
    StageArtifactBinding,
    StageArtifactInput,
    StageArtifactOutput,
    StageIdempotencePolicy,
    StageKindModelBinding,
    StageOverrideField,
    StageResultArtifact,
    StageRetryPolicy,
    StructuredStageResult,
    StructuredStageResultMetadata,
    TaskAuthoringProfileDefinition,
    TaskAuthoringProfilePayload,
    TaskBreadth,
    TaskDecompositionStyle,
)
