"""Sentinel incident rendering and persistence helpers."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from .markdown import write_text_atomic
from .paths import RuntimePaths
from .research.incident_document_rendering import _slugify
from .research.incident_documents import load_incident_document
from .research.persistence_helpers import _sha256_text
from .sentinel_models import SentinelIncidentBundle, SentinelIncidentPayload, SentinelReport, SentinelState


def _relative_path(path: Path, *, root: Path) -> str:
    try:
        return path.resolve().relative_to(root.resolve()).as_posix()
    except ValueError:
        return path.resolve().as_posix()


def _incident_title(summary: str) -> str:
    text = " ".join(summary.strip().split())
    if not text:
        return "Sentinel incident"
    return text[0].upper() + text[1:]


def _incident_id(payload: SentinelIncidentPayload, *, emitted_at: datetime) -> str:
    route = payload.routing_target.upper()
    timestamp = emitted_at.astimezone(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    digest = _sha256_text(f"{payload.failure_signature}|{payload.summary}|{payload.routing_target}")[:8].upper()
    return f"INC-SENTINEL-{route}-{timestamp}-{digest}"


def _incident_markdown(
    *,
    payload: SentinelIncidentPayload,
    incident_id: str,
    incident_path: str,
    bundle_path: str,
    emitted_at: datetime,
) -> str:
    timestamp = emitted_at.astimezone(timezone.utc).isoformat().replace("+00:00", "Z")
    title = _incident_title(payload.summary)
    fingerprint = _sha256_text(
        "|".join(
            [
                payload.failure_signature,
                payload.summary,
                payload.severity,
                payload.routing_target,
                "|".join(payload.evidence_pointers),
            ]
        )
    )
    source_task = payload.sentinel_check_id or payload.recovery_request_id or "sentinel-manual"
    marker_lines = [
        f"- `{marker.plane}` status: `{marker.marker or 'unknown'}`"
        + (f" from `{marker.source_path}`" if marker.source_path else "")
        for marker in payload.observed_status_markers
    ]
    evidence_lines = [f"- `{bundle_path}`", f"- Incident path target: `{incident_path}`"]
    if payload.sentinel_report_path:
        evidence_lines.append(f"- Sentinel report: `{payload.sentinel_report_path}`")
    if payload.sentinel_state_path:
        evidence_lines.append(f"- Sentinel state: `{payload.sentinel_state_path}`")
    if payload.recovery_request_id:
        evidence_lines.append(f"- Linked recovery request: `{payload.recovery_request_id}`")
    evidence_lines.extend(f"- `{pointer}`" for pointer in payload.evidence_pointers)
    if not marker_lines:
        marker_lines.append("- No durable status markers were available at generation time.")
    suggested_recovery = (
        payload.suggested_recovery
        or f"Queue or continue `{payload.routing_target}` recovery through the supported recovery control surface."
    )
    return "\n".join(
        [
            "---",
            f"incident_id: {incident_id}",
            "status: incoming",
            f"severity: {payload.severity}",
            f"fingerprint: {fingerprint}",
            f"failure_signature: {payload.failure_signature}",
            f"source_task: sentinel :: {source_task}",
            f"opened_at: {timestamp}",
            f"updated_at: {timestamp}",
            "source: sentinel",
            f"routing_target: {payload.routing_target}",
            f"recovery_request_id: {payload.recovery_request_id}",
            f"sentinel_check_id: {payload.sentinel_check_id}",
            f"sentinel_report_path: {payload.sentinel_report_path}",
            f"sentinel_state_path: {payload.sentinel_state_path}",
            f"sentinel_bundle_path: {bundle_path}",
            "---",
            "",
            f"# {title}",
            "",
            "## Summary",
            f"- {payload.summary}",
            f"- Generated by Sentinel for routing target `{payload.routing_target}`.",
            "",
            "## Impact",
            f"- Sentinel classified this workspace as `{payload.report_status}` because `{payload.report_reason or payload.summary}`.",
            f"- No meaningful progress was observed for `{payload.elapsed_since_last_progress_seconds}` seconds.",
            "",
            "## Trigger",
            f"- Failure signature: `{payload.failure_signature}`",
            f"- Source: `{payload.source}`",
            f"- Routing target: `{payload.routing_target}`",
            "",
            "## Evidence",
            *evidence_lines,
            "",
            "## Reproduction",
            "1. Re-read the linked Sentinel report and current status markers.",
            "2. Confirm that the listed evidence pointers still reflect the same stalled or degraded state.",
            "3. Continue with the routed recovery path only if the workspace still matches this incident.",
            "",
            "## Hypothesis",
            f"- Sentinel's bounded diagnosis indicates `{payload.failure_signature}` and recommends `{payload.routing_target}` as the next recovery surface.",
            "",
            "## Alternative Hypotheses",
            "- AH-01: The workspace recovered after the last Sentinel check.",
            "  - Status: candidate",
            "  - Evidence: Re-run `millrace sentinel check --json` before deeper intervention.",
            "",
            "## Investigation",
            "- Steps:",
            "  1. Review the Sentinel report and recent event/history evidence.",
            "  2. Compare the linked recovery request and incident route with current runtime state.",
            "- Findings:",
            *marker_lines,
            "",
            "## Governance Routing",
            f"- Severity Class: {payload.severity}",
            f"- preemption behavior: {payload.severity} follows the standard incident governance contract.",
            "- Incident Class: other",
            f"- minimal-unblock-first path: {suggested_recovery}",
            "- rewrite task card path: n/a",
            "- spec addendum backflow: n/a",
            "- regression test requirement: required if the routed remediation reveals a product bug.",
            "- regression test evidence: pending",
            "- framework-level routing: n/a",
            "",
            "## Unsupported Hypotheses",
            "- AH-99",
            "  - Status: unsupported",
            "  - Evidence: no counter-evidence captured at generation time",
            "",
            "## Resolution Criteria",
            "- The workspace either resumes meaningful progress or this incident is superseded by a more specific resolved incident.",
            "",
            "## Follow-ups",
            f"- If `{payload.routing_target}` is queued separately, preserve linkage to `{payload.recovery_request_id or 'the future recovery request id'}`.",
            "",
        ]
    )


def _link_persisted_sentinel_artifacts(
    paths: RuntimePaths,
    *,
    incident_id: str,
    incident_path: str,
    recovery_request_id: str,
) -> bool:
    linked = False
    if paths.sentinel_state_file.exists():
        state = SentinelState.model_validate_json(paths.sentinel_state_file.read_text(encoding="utf-8"))
        updated_state = state.model_copy(
            update={
                "last_incident_id": incident_id,
                "last_incident_path": incident_path,
                "last_recovery_request_id": recovery_request_id,
            }
        )
        write_text_atomic(paths.sentinel_state_file, updated_state.model_dump_json(indent=2) + "\n")
        linked = True
    if paths.sentinel_summary_file.exists():
        summary = SentinelReport.model_validate_json(
            paths.sentinel_latest_report_file.read_text(encoding="utf-8")
        ).summary if paths.sentinel_latest_report_file.exists() else None
        if summary is not None:
            updated_summary = summary.model_copy(
                update={
                    "queued_recovery_request_id": recovery_request_id,
                    "last_incident_id": incident_id,
                    "last_incident_path": incident_path,
                }
            )
            write_text_atomic(paths.sentinel_summary_file, updated_summary.model_dump_json(indent=2) + "\n")
            linked = True
    if paths.sentinel_latest_report_file.exists():
        report = SentinelReport.model_validate_json(paths.sentinel_latest_report_file.read_text(encoding="utf-8"))
        updated_report = report.model_copy(
            update={
                "summary": report.summary.model_copy(
                    update={
                        "queued_recovery_request_id": recovery_request_id,
                        "last_incident_id": incident_id,
                        "last_incident_path": incident_path,
                    }
                )
            }
        )
        write_text_atomic(paths.sentinel_latest_report_file, updated_report.model_dump_json(indent=2) + "\n")
        linked = True
    return linked


def persist_sentinel_incident(
    paths: RuntimePaths,
    *,
    payload: SentinelIncidentPayload,
    issuer: str,
    emitted_at: datetime,
    incident_id: str | None = None,
    command_id: str = "",
) -> SentinelIncidentBundle:
    """Persist one Sentinel-authored incident and its structured sidecar bundle."""

    incident_id = incident_id or _incident_id(payload, emitted_at=emitted_at)
    incident_path = paths.ideas_dir / "incidents" / "incoming" / f"{incident_id}.md"
    bundle_path = paths.sentinel_incident_bundles_dir / f"{incident_id}.json"
    incident_rel_path = _relative_path(incident_path, root=paths.root)
    bundle_rel_path = _relative_path(bundle_path, root=paths.root)
    markdown = _incident_markdown(
        payload=payload,
        incident_id=incident_id,
        incident_path=incident_rel_path,
        bundle_path=bundle_rel_path,
        emitted_at=emitted_at,
    )
    incident_path.parent.mkdir(parents=True, exist_ok=True)
    paths.sentinel_incident_bundles_dir.mkdir(parents=True, exist_ok=True)
    write_text_atomic(incident_path, markdown + "\n")
    load_incident_document(incident_path)
    linked = _link_persisted_sentinel_artifacts(
        paths,
        incident_id=incident_id,
        incident_path=incident_rel_path,
        recovery_request_id=payload.recovery_request_id,
    )
    bundle = SentinelIncidentBundle(
        emitted_at=emitted_at,
        incident_id=incident_id,
        incident_path=incident_rel_path,
        bundle_path=bundle_rel_path,
        issuer=issuer,
        command_id=command_id,
        payload=payload,
        linked_to_persisted_sentinel_state=linked,
    )
    write_text_atomic(bundle_path, bundle.model_dump_json(indent=2) + "\n")
    return bundle


__all__ = ["persist_sentinel_incident"]
