"""Shared GoalSpec stage rendering helpers."""

from __future__ import annotations

from datetime import datetime

from .goalspec import (
    AcceptanceProfileRecord,
    GoalSource,
    ObjectiveProfileSyncStateRecord,
)
from .goalspec_helpers import (
    _FRONTMATTER_BOUNDARY,
    _first_paragraph,
    _isoformat_z,
)


def render_queue_spec(
    *,
    emitted_at: datetime,
    source: GoalSource,
    spec_id: str,
    objective_state: ObjectiveProfileSyncStateRecord,
    profile: AcceptanceProfileRecord,
    completion_manifest_path: str,
) -> str:
    summary = _first_paragraph(source.body) or source.title
    hard_blocker_lines = [f"- {item}" for item in profile.hard_blockers] or ["- No explicit blockers were recorded."]
    timestamp = _isoformat_z(emitted_at)
    return "\n".join(
        [
            _FRONTMATTER_BOUNDARY,
            f"spec_id: {spec_id}",
            f"idea_id: {source.idea_id}",
            f"title: {source.title}",
            "status: proposed",
            "golden_version: 1",
            f"base_goal_sha256: {source.checksum_sha256}",
            "effort: 3",
            f"decomposition_profile: {source.decomposition_profile}",
            "depends_on_specs: []",
            "owner: research",
            f"created_at: {timestamp}",
            f"updated_at: {timestamp}",
            _FRONTMATTER_BOUNDARY,
            "",
            "## Summary",
            summary,
            "",
            "## Goals",
            f"- Convert `{source.idea_id}` into a traceable GoalSpec draft package.",
            "- Preserve objective-profile inputs and the completion-manifest plan in emitted spec artifacts.",
            *(f"- {item}" for item in profile.milestones),
            "",
            "## Non-Goals",
            "- Spec Review decisions.",
            "- Task generation and pending shard emission.",
            "",
            "## Scope",
            "### In Scope",
            "- Completion-manifest draft persistence for this GoalSpec source.",
            "- One queue spec plus stable golden and phase copies for downstream review.",
            "- Family-state initialization for the emitted draft spec.",
            "",
            "### Out of Scope",
            "- Approval, merge, or backlog handoff.",
            "- Additional spec families beyond this initial emitted spec.",
            "",
            "## Capability Domains",
            "- GoalSpec runtime execution",
            "- Durable artifact traceability",
            "",
            "## Decomposition Readiness",
            "- This synthesized scope is intentionally bounded to one emitted spec for Run 03.",
            f"- Declared decomposition profile: `{source.decomposition_profile}`.",
            "- Later review/task-generation stages remain downstream of this draft package.",
            "",
            "## Constraints",
            "- Preserve linkage back to the staged goal and objective profile inputs.",
            "- Keep research-plane runtime behavior restart-safe and deterministic.",
            "- Avoid pulling Spec Review or task generation into this run.",
            "",
            "## Implementation Plan",
            "1. Draft the completion manifest from the staged goal and objective profile.",
            "2. Emit queue, golden, and phase spec artifacts for one spec candidate.",
            "3. Persist spec-family state and a synthesis decision record for downstream review.",
            "",
            "## Requirements Traceability (Req-ID Matrix)",
            (
                f"- `Req-ID: REQ-001` | Preserve linkage to `{source.idea_id}` intake/objective inputs | "
                f"`{objective_state.profile_path}`"
            ),
            (
                f"- `Req-ID: REQ-002` | Persist completion-manifest drafting state before spec output | "
                f"`{completion_manifest_path}`"
            ),
            "",
            "## Assumptions Ledger",
            "- The first initial-family emission for this goal remains a single-spec family in Run 03 (source: inferred).",
            "- Objective-profile milestones are sufficient context for a draft spec package at this stage (source: confirmed).",
            "",
            "## Structured Decision Log",
            "| decision_id | phase_key | phase_priority | status | owner | rationale | timestamp |",
            "| --- | --- | --- | --- | --- | --- | --- |",
            f"| DEC-001 | PHASE_01 | P1 | proposed | research | Emit one bounded draft spec before Spec Review | {timestamp} |",
            "",
            "## Interrogation Record",
            "- Critic question: what is the smallest durable spec package that preserves GoalSpec traceability?",
            "- Designer resolution: emit one bounded spec with explicit links to the objective profile and completion manifest.",
            "",
            "## Verification",
            "- `python3 -c \"from pathlib import Path; assert Path('agents/audit/completion_manifest.json').exists(); assert Path('agents/reports/acceptance_profiles').exists()\"`",
            "- `python3 -c \"from pathlib import Path; assert any(Path('agents/specs/stable/golden').glob('*.md')); assert any(Path('agents/specs/stable/phase').glob('*.md'))\"`",
            "",
            "## Dependencies",
            f"- Objective profile: `{objective_state.profile_path}`",
            f"- Completion manifest draft: `{completion_manifest_path}`",
            "",
            "## Risks and Mitigations",
            "- Risk: later stages may require additional decomposition. Mitigation: family state remains explicit and editable in later runs.",
            "",
            "## Rollout and Rollback",
            "- Rollout: use this draft package as the input to Spec Review.",
            "- Rollback: discard the emitted draft artifacts and rerun GoalSpec synthesis from the staged brief.",
            "",
            "## Open Questions",
            *hard_blocker_lines,
            "",
            "## References",
            f"- Staged goal: `{source.relative_source_path}`",
            f"- Objective profile JSON: `{objective_state.profile_path}`",
            f"- Completion manifest draft: `{completion_manifest_path}`",
            "",
        ]
    )


def render_phase_spec(
    *,
    emitted_at: datetime,
    spec_id: str,
    title: str,
    completion_manifest_path: str,
    objective_profile_path: str,
) -> str:
    timestamp = _isoformat_z(emitted_at)
    return "\n".join(
        [
            _FRONTMATTER_BOUNDARY,
            f"phase_id: PHASE-{spec_id}-01",
            "phase_key: PHASE_01",
            "phase_priority: P1",
            f"parent_spec_id: {spec_id}",
            f"title: {title} Implementation Foundation",
            "status: planned",
            "owner: research",
            f"created_at: {timestamp}",
            f"updated_at: {timestamp}",
            _FRONTMATTER_BOUNDARY,
            "",
            "## Objective",
            "- Carry the drafted GoalSpec package into a reviewable runtime implementation slice.",
            "",
            "## Entry Criteria",
            f"- Completion manifest draft exists at `{completion_manifest_path}`.",
            f"- Objective profile exists at `{objective_profile_path}`.",
            "",
            "## Scope",
            "### In Scope",
            "- Finalize the bounded GoalSpec runtime surfaces declared by the draft spec.",
            "- Preserve traceability between the staged goal, completion manifest, and emitted spec artifacts.",
            "",
            "### Out of Scope",
            "- Spec Review approval.",
            "- Task generation.",
            "",
            "## Work Plan",
            "1. Validate the completion-manifest draft and objective profile against the emitted queue spec.",
            "2. Implement the bounded GoalSpec runtime deliverables declared by the draft package.",
            "3. Run targeted verification and hand the package to Spec Review.",
            "",
            "## Requirements Traceability (Req-ID)",
            f"- `Req-ID: REQ-001` traced through `{completion_manifest_path}`.",
            f"- `Req-ID: REQ-002` traced through `{objective_profile_path}`.",
            "",
            "## Assumptions Ledger",
            "- The emitted draft package remains a single-spec family through review (confidence: inferred).",
            "",
            "## Structured Decision Log",
            "| decision_id | phase_key | phase_priority | status | owner | rationale | timestamp |",
            "| --- | --- | --- | --- | --- | --- | --- |",
            f"| DEC-PHASE-001 | PHASE_01 | P1 | proposed | research | Preserve bounded Run 03 scope for the first draft spec family | {timestamp} |",
            "",
            "## Interrogation Notes",
            "- This phase exists to keep implementation work bounded and reviewable after draft synthesis.",
            "",
            "## Verification",
            "- Draft artifacts and family state remain mutually traceable.",
            "",
            "## Exit Criteria",
            "- The package is ready for Spec Review without inventing new scope.",
            "",
            "## Handoff",
            "- Feed the queue spec and this phase note into the next research stage.",
            "",
            "## Risks",
            "- Review may discover a need for additional later specs; if so, record them explicitly in a later run.",
            "",
        ]
    )


def render_synthesis_decision_record(
    *,
    emitted_at: datetime,
    run_id: str,
    source: GoalSource,
    spec_id: str,
    completion_manifest_path: str,
    objective_profile_path: str,
    queue_spec_path: str,
    family_complete: bool,
) -> str:
    timestamp = _isoformat_z(emitted_at)
    family_complete_text = "yes" if family_complete else "no"
    return "\n".join(
        [
            f"# Spec Synthesis: {source.title}",
            "",
            f"- **Run-ID:** {run_id}",
            f"- **Goal-ID:** {source.idea_id}",
            f"- **Spec-ID:** {spec_id}",
            f"- **Updated-At:** {timestamp}",
            "",
            "## Critic Questions",
            "- What is the smallest durable spec package that preserves GoalSpec traceability?",
            "- Which artifacts must exist before later review/task-generation work can proceed safely?",
            "",
            "## Designer Resolutions",
            "- Emit one bounded draft spec family for this goal in Run 03.",
            "- Preserve explicit links to the staged goal, objective profile, and completion manifest draft.",
            "",
            "## Retained Assumptions",
            "- Additional families are not required before Spec Review for this initial draft package.",
            "",
            "## Contradictions",
            "- None observed during deterministic synthesis.",
            "",
            "## Clarifier Preservation Statement",
            "- The emitted queue/golden/phase artifacts preserve the bounded decisions above without expanding scope.",
            "",
            "## Family Plan",
            "- Initial-family declaration: one emitted spec.",
            f"- Family complete after this run: `{family_complete_text}`",
            f"- Emitted spec: `{spec_id}` at `{queue_spec_path}`",
            "- Planned later specs: none",
            "",
            "## References",
            f"- Staged goal: `{source.relative_source_path}`",
            f"- Objective profile: `{objective_profile_path}`",
            f"- Completion manifest: `{completion_manifest_path}`",
            "",
        ]
    )


def render_spec_review_questions(
    *,
    reviewed_at: datetime,
    run_id: str,
    goal_id: str,
    spec_id: str,
    title: str,
    queue_spec_path: str,
    stable_spec_paths: tuple[str, ...],
) -> str:
    stable_lines = [f"- `{path}`" for path in stable_spec_paths] or ["- No stable spec copies were discovered."]
    return "\n".join(
        [
            "# Spec Review Questions",
            "",
            f"- **Run-ID:** {run_id}",
            f"- **Goal-ID:** {goal_id}",
            f"- **Spec-ID:** {spec_id}",
            f"- **Title:** {title}",
            f"- **Reviewed-At:** {_isoformat_z(reviewed_at)}",
            f"- **Queue-Spec:** `{queue_spec_path}`",
            "",
            "## Critic Findings",
            "- No material delta was required to make this package decomposition-ready.",
            "",
            "## Stable Spec Inputs",
            *stable_lines,
            "",
        ]
    )


def render_spec_review_decision(
    *,
    reviewed_at: datetime,
    run_id: str,
    goal_id: str,
    spec_id: str,
    title: str,
    review_status: str,
    reviewed_path: str,
    stable_registry_path: str,
    lineage_path: str,
) -> str:
    return "\n".join(
        [
            "# Spec Review Decision",
            "",
            f"- **Run-ID:** {run_id}",
            f"- **Goal-ID:** {goal_id}",
            f"- **Spec-ID:** {spec_id}",
            f"- **Title:** {title}",
            f"- **Review-Status:** `{review_status}`",
            f"- **Reviewed-At:** {_isoformat_z(reviewed_at)}",
            f"- **Reviewed-Spec:** `{reviewed_path}`",
            f"- **Stable-Registry:** `{stable_registry_path}`",
            f"- **Lineage-Record:** `{lineage_path}`",
            "",
            "## Decision",
            "- Approved for downstream decomposition without material spec edits in this run.",
            "",
        ]
    )
