"""Progress-watchdog helpers for the research governance facade."""

from __future__ import annotations

from pathlib import Path
from typing import Literal

from ..contracts import TaskCard
from ..markdown import TaskStoreDocument, parse_task_store, render_task_store, write_text_atomic
from ..paths import RuntimePaths
from ..queue import load_research_recovery_latch


def _read_task_store_cards(path: Path) -> tuple[TaskCard, ...]:
    if not path.exists():
        return ()
    return tuple(parse_task_store(path.read_text(encoding="utf-8"), source_file=path).cards)


def _visible_recovery_cards(paths: RuntimePaths, *, remediation_spec_id: str) -> tuple[TaskCard, ...]:
    cards: list[TaskCard] = []
    for store_path in (paths.tasks_file, paths.backlog_file, paths.taskspending_file):
        cards.extend(card for card in _read_task_store_cards(store_path) if card.spec_id == remediation_spec_id)
    return tuple(cards)


def _append_backlog_task(paths: RuntimePaths, *, title: str, body: str, spec_id: str) -> TaskCard:
    from .governance import _utcnow

    task_date = _utcnow().date().isoformat()
    card = TaskCard.model_validate(
        {
            "heading": f"## {task_date} - {title}",
            "body": f"- **Spec-ID:** {spec_id}\n\n{body.strip()}",
        }
    )
    backlog_document = parse_task_store(
        paths.backlog_file.read_text(encoding="utf-8"),
        source_file=paths.backlog_file,
    )
    updated = TaskStoreDocument(preamble=backlog_document.preamble, cards=[*backlog_document.cards, card])
    write_text_atomic(paths.backlog_file, render_task_store(updated))
    return card


def _governance_history_status(paths: RuntimePaths) -> tuple[bool | None, str]:
    from .governance import _load_json_object
    from .specs import GoalSpecFamilyState

    if not paths.goal_spec_family_state_file.exists():
        return None, "goal-spec-family-state-missing"
    if not paths.objective_family_policy_file.exists():
        return None, "family-policy-file-missing"
    family_state = GoalSpecFamilyState.model_validate(_load_json_object(paths.goal_spec_family_state_file))
    plan = family_state.initial_family_plan
    if plan is None or not plan.frozen:
        return None, "no-active-frozen-family-policy-history"
    return True, "frozen-family-policy-history-preserved"


def _resolve_record_path(path_token: str | Path, *, relative_to: Path) -> Path:
    candidate = Path(path_token)
    if candidate.is_absolute():
        return candidate
    return relative_to / candidate


def _regenerate_audit_recovery_task(
    paths: RuntimePaths,
    *,
    remediation_record_path: Path,
    remediation_spec_id: str,
    visible_count_before: int,
):
    from .audit import AuditRemediationRecord
    from .governance import (
        RecoveryTaskRegenerationReport,
        _file_sha256_or_none,
        _load_json_object,
        _relative_path,
    )

    if not remediation_record_path.exists():
        preserved, preservation_reason = _governance_history_status(paths)
        return RecoveryTaskRegenerationReport(
            status="manual_only",
            reason="audit-remediation-record-missing",
            decision_type="durable_remediation_decision",
            remediation_spec_id=remediation_spec_id,
            remediation_record_path=_relative_path(remediation_record_path, relative_to=paths.root),
            visible_task_count_before=visible_count_before,
            visible_task_count_after=visible_count_before,
            family_policy_path=_relative_path(paths.objective_family_policy_file, relative_to=paths.root),
            spec_family_state_path=_relative_path(paths.goal_spec_family_state_file, relative_to=paths.root),
            family_policy_history_preserved=preserved,
            family_policy_history_reason=preservation_reason,
        )

    remediation_record = AuditRemediationRecord.model_validate(_load_json_object(remediation_record_path))
    before_policy_hash = _file_sha256_or_none(paths.objective_family_policy_file)
    before_family_state_hash = _file_sha256_or_none(paths.goal_spec_family_state_file)
    body = "\n".join(
        [
            f"- **Goal:** Restore governed audit remediation work for `{remediation_record.audit_id}`.",
            (
                "- **Context:** Regenerated by the progress watchdog from "
                f"`{_relative_path(remediation_record_path, relative_to=paths.root)}` "
                "after the frozen recovery batch no longer had visible remediation work."
            ),
            (
                "- **Acceptance:** Follow the durable remediation record and re-check the backlog/audit path "
                f"documented at `{_relative_path(remediation_record_path, relative_to=paths.root)}`."
            ),
            f"- **Notes:** Original remediation task id was `{remediation_record.remediation_task_id}`.",
        ]
    )
    regenerated_card = _append_backlog_task(
        paths,
        title=remediation_record.remediation_task_title,
        body=body,
        spec_id=remediation_record.remediation_spec_id,
    )
    after_policy_hash = _file_sha256_or_none(paths.objective_family_policy_file)
    after_family_state_hash = _file_sha256_or_none(paths.goal_spec_family_state_file)
    preserved = before_policy_hash == after_policy_hash and before_family_state_hash == after_family_state_hash
    return RecoveryTaskRegenerationReport(
        status="regenerated",
        reason="audit-remediation-task-regenerated",
        decision_type="durable_remediation_decision",
        remediation_spec_id=remediation_record.remediation_spec_id,
        remediation_record_path=_relative_path(remediation_record_path, relative_to=paths.root),
        visible_task_count_before=visible_count_before,
        visible_task_count_after=len(
            _visible_recovery_cards(paths, remediation_spec_id=remediation_record.remediation_spec_id)
        ),
        regenerated_task_id=regenerated_card.task_id,
        regenerated_task_title=regenerated_card.title,
        family_policy_path=_relative_path(paths.objective_family_policy_file, relative_to=paths.root),
        spec_family_state_path=_relative_path(paths.goal_spec_family_state_file, relative_to=paths.root),
        family_policy_history_preserved=preserved,
        family_policy_history_reason=(
            "frozen-family-policy-history-preserved"
            if preserved
            else "unexpected-family-policy-history-mutation"
        ),
    )


def _evaluate_recovery_regeneration(
    paths: RuntimePaths,
    *,
    decision_type: Literal["regenerated_backlog_work", "durable_remediation_decision"],
    remediation_spec_id: str,
    remediation_record_path: Path,
    taskaudit_record_path: str,
    task_provenance_path: str,
    lineage_path: str,
    visible_count_before: int,
    allow_regeneration: bool,
):
    from .governance import RecoveryTaskRegenerationReport, _relative_path

    preserved, preservation_reason = _governance_history_status(paths)
    base_report = RecoveryTaskRegenerationReport(
        reason="recovery-regeneration-not-applicable",
        decision_type=decision_type,
        remediation_spec_id=remediation_spec_id,
        remediation_record_path=_relative_path(remediation_record_path, relative_to=paths.root),
        taskaudit_record_path=taskaudit_record_path,
        task_provenance_path=task_provenance_path,
        lineage_path=lineage_path,
        visible_task_count_before=visible_count_before,
        visible_task_count_after=visible_count_before,
        family_policy_path=_relative_path(paths.objective_family_policy_file, relative_to=paths.root),
        spec_family_state_path=_relative_path(paths.goal_spec_family_state_file, relative_to=paths.root),
        family_policy_history_preserved=preserved,
        family_policy_history_reason=preservation_reason,
    )
    if visible_count_before > 0:
        return base_report.model_copy(
            update={
                "status": "not_needed",
                "reason": "visible-recovery-work-present",
            }
        )
    if decision_type == "durable_remediation_decision":
        if not allow_regeneration:
            return base_report.model_copy(
                update={
                    "status": "manual_only",
                    "reason": "durable-recovery-task-missing",
                }
            )
        return _regenerate_audit_recovery_task(
            paths,
            remediation_record_path=remediation_record_path,
            remediation_spec_id=remediation_spec_id,
            visible_count_before=visible_count_before,
        )
    return base_report.model_copy(
        update={
            "status": "manual_only",
            "reason": "regenerated-family-work-missing",
        }
    )


def evaluate_progress_watchdog(
    *,
    paths: RuntimePaths,
    allow_regeneration: bool = False,
):
    """Evaluate one explainable progress-watchdog snapshot over the recovery latch."""

    from .governance import (
        ProgressWatchdogReport,
        _normalize_optional_text,
        _relative_path,
        _utcnow,
    )

    latch = load_research_recovery_latch(paths.research_recovery_latch_file)
    report = ProgressWatchdogReport(
        updated_at=_utcnow(),
        report_path=_relative_path(paths.progress_watchdog_report_file, relative_to=paths.root),
        state_path=_relative_path(paths.progress_watchdog_state_file, relative_to=paths.root),
        latch_path=_relative_path(paths.research_recovery_latch_file, relative_to=paths.root),
        reason="no-research-recovery-latch",
    )
    if latch is None:
        return report

    report = report.model_copy(
        update={
            "batch_id": latch.batch_id,
            "reason": "frozen-batch-awaiting-remediation-decision",
        }
    )
    decision = latch.remediation_decision
    if decision is None:
        return report.model_copy(
            update={
                "status": "waiting",
                "escalation_action": "monitor",
            }
        )

    visible_count_before = len(_visible_recovery_cards(paths, remediation_spec_id=decision.remediation_spec_id))
    regeneration_report = _evaluate_recovery_regeneration(
        paths,
        decision_type=decision.decision_type,
        remediation_spec_id=decision.remediation_spec_id,
        remediation_record_path=_resolve_record_path(decision.remediation_record_path, relative_to=paths.root),
        taskaudit_record_path=_normalize_optional_text(
            None if decision.taskaudit_record_path is None else decision.taskaudit_record_path.as_posix()
        ),
        task_provenance_path=_normalize_optional_text(
            None if decision.task_provenance_path is None else decision.task_provenance_path.as_posix()
        ),
        lineage_path=_normalize_optional_text(
            None if decision.lineage_path is None else decision.lineage_path.as_posix()
        ),
        visible_count_before=visible_count_before,
        allow_regeneration=allow_regeneration,
    )
    visible_count_after = len(_visible_recovery_cards(paths, remediation_spec_id=decision.remediation_spec_id))
    if visible_count_after > 0:
        return report.model_copy(
            update={
                "status": "regenerated" if regeneration_report.status == "regenerated" else "ready",
                "reason": (
                    "durable-recovery-task-regenerated"
                    if regeneration_report.status == "regenerated"
                    else "visible-recovery-work-present"
                ),
                "recovery_decision_type": decision.decision_type,
                "remediation_spec_id": decision.remediation_spec_id,
                "visible_recovery_task_count": visible_count_after,
                "expected_pending_card_count": decision.pending_card_count,
                "expected_backlog_card_count": decision.backlog_card_count,
                "escalation_action": "none" if regeneration_report.status != "regenerated" else "regenerate_task",
                "recovery_regeneration": regeneration_report,
            }
        )
    return report.model_copy(
        update={
            "status": "stalled",
            "reason": "visible-recovery-work-missing",
            "recovery_decision_type": decision.decision_type,
            "remediation_spec_id": decision.remediation_spec_id,
            "visible_recovery_task_count": 0,
            "expected_pending_card_count": decision.pending_card_count,
            "expected_backlog_card_count": decision.backlog_card_count,
            "escalation_action": (
                "regenerate_task"
                if decision.decision_type == "durable_remediation_decision"
                else "manual_review"
            ),
            "recovery_regeneration": regeneration_report,
        }
    )


def sync_progress_watchdog(
    *,
    paths: RuntimePaths,
    allow_regeneration: bool = False,
):
    """Persist one progress-watchdog snapshot for engine-side visibility."""

    from .governance import ProgressWatchdogState

    report = evaluate_progress_watchdog(paths=paths, allow_regeneration=allow_regeneration)
    state = ProgressWatchdogState(
        updated_at=report.updated_at,
        batch_id=report.batch_id,
        status=report.status,
        reason=report.reason,
        remediation_spec_id=report.remediation_spec_id,
        visible_recovery_task_count=report.visible_recovery_task_count,
        escalation_action=report.escalation_action,
    )
    paths.progress_watchdog_state_file.parent.mkdir(parents=True, exist_ok=True)
    paths.progress_watchdog_report_file.parent.mkdir(parents=True, exist_ok=True)
    write_text_atomic(paths.progress_watchdog_state_file, state.model_dump_json(indent=2) + "\n")
    write_text_atomic(paths.progress_watchdog_report_file, report.model_dump_json(indent=2) + "\n")
    return report
