"""Additive loop-architecture contracts and helpers."""

from millrace_ai.architecture.loop_graphs import (
    GraphLoopCompletionBehaviorDefinition,
    GraphLoopCounterName,
    GraphLoopDefinition,
    GraphLoopDynamicPoliciesDefinition,
    GraphLoopEdgeDefinition,
    GraphLoopEdgeKind,
    GraphLoopEntryDefinition,
    GraphLoopEntryKey,
    GraphLoopNodeDefinition,
    GraphLoopResumePolicyDefinition,
    GraphLoopTerminalClass,
    GraphLoopTerminalStateDefinition,
    GraphLoopThresholdPolicyDefinition,
)
from millrace_ai.architecture.materialization import (
    CompiledGraphCompletionEntryPlan,
    CompiledGraphEntryPlan,
    CompiledGraphResumePolicyPlan,
    CompiledGraphThresholdPolicyPlan,
    CompiledGraphTransitionPlan,
    FrozenGraphPlanePlan,
    FrozenGraphRunPlan,
    MaterializedGraphNodePlan,
)
from millrace_ai.architecture.stage_kinds import (
    ArchitectureContractModel,
    RecoveryRole,
    RegisteredStageKindDefinition,
    StageIdempotencePolicy,
)

__all__ = [
    "ArchitectureContractModel",
    "CompiledGraphCompletionEntryPlan",
    "CompiledGraphEntryPlan",
    "CompiledGraphResumePolicyPlan",
    "CompiledGraphThresholdPolicyPlan",
    "CompiledGraphTransitionPlan",
    "FrozenGraphPlanePlan",
    "FrozenGraphRunPlan",
    "GraphLoopCounterName",
    "GraphLoopCompletionBehaviorDefinition",
    "GraphLoopDynamicPoliciesDefinition",
    "GraphLoopDefinition",
    "GraphLoopEdgeDefinition",
    "GraphLoopEdgeKind",
    "GraphLoopEntryDefinition",
    "GraphLoopEntryKey",
    "GraphLoopNodeDefinition",
    "GraphLoopResumePolicyDefinition",
    "GraphLoopTerminalClass",
    "GraphLoopTerminalStateDefinition",
    "GraphLoopThresholdPolicyDefinition",
    "MaterializedGraphNodePlan",
    "RecoveryRole",
    "RegisteredStageKindDefinition",
    "StageIdempotencePolicy",
]
